### ISSUE TITLE
Add ID, titles and descriptions into SVG paths.

### ISSUE THREAD

**Issue by rrudol** [akai-org/map#1]
More information here: http://www.mcp.poznan.pl/funkcje-karty-els/informator-dla-studenow-pp/

**Comment by mateusz-stempniewicz** [comment]
@rrudol, wrzuciłem wygenerowany SVG prosto z OSM. Niestety wydaje mi się całkowicie bezużyteczny do jakiejkolwiek edycji ręcznej

**Comment by rrudol** [comment]
@Mateusz-Stempniewicz zależy co chcemy edytować. Na pewno nie ma problemu ze zidentyfikowaniem ścieżek. Np. wydział chemii to path12547 - możemy pozmieniać identyfikatory, a mając je możemy już stylować i animować obiekty. Zdaje się, że możemy się też podpiąć eventami JSowymi.
