### ISSUE TITLE
Get data of buildings

### ISSUE THREAD

**Issue by rrudol** [akai-org/map#12]

**Comment by hejmsdz** [comment]
Chodzi o kształty budynków do podświetlania? Można je wyciągnąć prosto z danych OpenStreetMap.
Pod adresem typu http://www.openstreetmap.org/api/0.6/way/300946610 (tu Wydział Technologii Chemicznej) jest opis ścieżki, każdy Node jest pod adresem http://www.openstreetmap.org/api/0.6/node/3050532415 i tam już siedzą współrzędne. Ściągnięcie tego to kwestia napisania kilkudziesięciolinijkowego skryptu.

**Comment by hejmsdz** [comment]
Ech, spóźniłem się :|

**Comment by hejmsdz** [comment]
Temat wraca, bo trzeba opracować pozostałe kampusy.
