### ISSUE TITLE
change sidebar close icon

### ISSUE THREAD

**Issue by rrudol** [akai-org/map#31]
X sign could be better.
<img width="302" alt="zrzut ekranu 2017-03-14 o 19 19 15" src="https://cloud.githubusercontent.com/assets/9325182/23916050/2e1797e6-08eb-11e7-8dcf-973a829f8d69.png">

**Comment by rrudol** [comment]
and shadow
<img width="189" alt="zrzut ekranu 2017-03-14 o 19 20 41" src="https://cloud.githubusercontent.com/assets/9325182/23916081/568bd49e-08eb-11e7-8950-947534f9d5dc.png">

**Comment by tomaszgil** [comment]
Changes on branch style-fix.
