### ISSUE TITLE
fix styling of top-bar

### ISSUE THREAD

**Issue by rrudol** [akai-org/map#34]
<img width="775" alt="zrzut ekranu 2017-03-14 o 19 28 17" src="https://cloud.githubusercontent.com/assets/9325182/23916425/72223ec2-08ec-11e7-9c18-72cad87b95c4.png">

**Comment by rrudol** [comment]
height of map (now it's scrollable)

**Comment by tomaszgil** [comment]
On branch 'style-fix' I've already changed the hamburger icon to a thinner version.

**Comment by rrudol** [comment]
I fixed it, but it crashed landing page idea. Body tag should get class depending on current view to fix it.
